project:
  type: website
  output-dir: docs
  #pre-render: python/replace_strings.py  
  preview:
    port: 7777
  render:
    - "*.qmd"
    - "!book/"

website:
    title: "Articoli di astronomia"
    favicon: book/images/logo.jpeg
    site-url: https://alexfum75.github.io/prova3
    navbar: 
        background: light
        pinned: false
        right:
          - href: index.qmd
            text: Home
          - href: Menu/LunaMarte.qmd
            text: Perché la Luna
          - href: Menu/friends.qmd
            text: "Link esterni"
          - text: "Astronomia e arte"
            menu:
              - text: "De Sphaera"
                href: Menu/DeSphaera.qmd
              - text: "La Divina Commedia"
                href: Menu/Dante.qmd
          - href: Menu/blog.qmd
            text: Blog
          - icon: linkedin
            href: https://www.linkedin.com/in/alessandrofumagalli

format:
  html:
    fontsize: 14pt 
    mainfont: "Georgia, sans-serif;"
    theme:         
        light: cosmos        
        dark: solar
    
    js: scripts.js
    css: book/css/styles.css
    toc: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    #include-in-header: analytics.html
    #page-layout: full
    grid:
      body-width: 1200px  # Imposta la larghezza desiderata in pixel o percentuale
      margin-width: 300px    
    filters:
      - abstract-section

execution:
  engine: jupyter
  freeze: auto  # Recommended: prevents re-running code on every site build unless modified      