project:
  type: website
  output-dir: docs
  pre-render: python/replace_strings.py  
  preview:
    port: 7777
  render:
    - "*.qmd"
    - "!book/"

website:
    title: "Articoli di astronomia"
    favicon: images/logo.jpeg
    site-url: https://alexfum75.github.io/prova3
    navbar: 
        background: white
        pinned: false
        right:
          - href: index.qmd
            text: Home
          - href: LunaMarte.qmd
            text: Perché la Luna
          - href: friends/friends.qmd
            text: Link
          - href: blog.qmd
            text: Blog
          - icon: linkedin
            href: https://www.linkedin.com/in/alessandrofumagalli

format:
  html:
    fontsize: 17px 
    mainfont: "Armarialbold, sans-serif;"
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnfonts.com">
    theme: 
      - cosmos
      - custom.scss
    js: scripts.js
    css: css/styles.css
    toc: true
    html-math-method: katex
    smooth-scroll: true
    anchor-sections: true
    #include-in-header: analytics.html
    page-layout: full
    filters:
      - abstract-section

execution:
  engine: jupyter
  freeze: auto  # Recommended: prevents re-running code on every site build unless modified      