---
title: ""
css: css/about.css
---

<h2>Informativa Privacy (art.13 D.Lgs. 196/2003 e seguenti)</h2>


::: {style="background-color: #f0e4cc; padding: 5px; border-radius: 8px; border: 1px solid #eee;"}
::: {.drop-cap}

I dati che i partecipanti al Blog conferiscono all’atto della loro iscrizione sono limitati all’ indirizzo e-mail e sono obbligatori al fine di ricevere la notifica di pubblicazione di un post. Per poter postare un commento invece, oltre all’email, è richiesto l’inserimento di nome e cognome, che possono anche non essere pubblicati insieme al commento postato dall’utente, mentre l’indirizzo e-mail viene utilizzato esclusivamente per l’invio delle news del sito.
:::
Le opinioni ed i commenti postati dagli utenti e le informazioni e i dati in esso contenuti non saranno destinati ad altro scopo che alla loro pubblicazione sul blog, in particolare, non ne è prevista l’aggregazione o selezione in specifiche banche dati. Eventuali trattamenti a fini statistici che in futuro possa essere intenzione del sito eseguire saranno condotti esclusivamente su base anonima.

Mentre la diffusione dei dati anagrafici dell’utente e di quelli rilevabili dai commenti postati deve intendersi direttamente attribuita alla iniziativa dell’utente medesimo, garantiamo che nessuna altra ipotesi di trasmissione o diffusione degli stessi è, dunque, prevista. In ogni caso, l’utente ha in ogni momento la possibilità di esercitare i diritti di cui all’ art. 7 del D.Lgs. 196/2003.

Per far valere tali diritti, l’Utente può rivolgersi direttamente al Titolare del Trattamento dei Dati personali all’indirizzo t99afi at gmail punto com

:::

---

{{< include footer.qmd >}}