---
title: ""
css: css/custom.css    
format:
  html:
    page-layout: full
---

<h2>Conferenze</h2>

<style>
/* Rende l'intestazione fissa in alto durante lo scorrimento verticale */
.table-scroll-container th {
    position: sticky;
    top: 0;
    background-color: #ffffff; /* Sfondo coprente per non far sovrapporre il testo sotto */
    z-index: 10;               /* Mantiene l'intestazione sopra le altre righe */
    box-shadow: inset 0 -2px 0 #ccc; /* Opzionale: aggiunge una linea di separazione sotto i titoli */
}
</style>

::: {.table-responsive style="max-height: 550px; overflow-y: auto;"}

| Anno | Titolo conferenza  | Registrazione | 
| :--: | :--- | :---: | 
| **2025** | Apollo 13: il problema, le soluzioni e la missione (1/3) | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px; border-radius: 20px;  text-decoration: none;" onclick="showVideo('Apollo13_1')">Registrazione</button> |
| | Apollo 13: il problema, le soluzioni e la missione (2/3) | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px; border-radius: 20px;  text-decoration: none;" onclick="showVideo('Apollo13_2')">Registrazione</button> |
| | Apollo 13: il problema, le soluzioni e la missione (3/3) | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px; border-radius: 20px;  text-decoration: none;" onclick="showVideo('Apollo13_3')">Registrazione</button> |
| **2024** | Apollo 8: politica uomini e missione (1/3) | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px; border-radius: 20px;  text-decoration: none;" onclick="showVideo('Apollo8_1')">Registrazione</button> |
| | Apollo 8: politica uomini e missione (2/3) | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px; border-radius: 20px;  text-decoration: none;" onclick="showVideo('Apollo8_2')">Registrazione</button> |
| | Apollo 8: politica uomini e missione (3/3) | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px; border-radius: 20px;  text-decoration: none;" onclick="showVideo('Apollo8_3)">Registrazione</button> |
| **2023** | Un filtro per la Luna | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px; border-radius: 20px;  text-decoration: none;" onclick="showVideo('FiltroLune')">Sommario</button> |
| | La Biglia Blu | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px;border-radius: 20px;  text-decoration: none;" onclick="showVideo('BibliaBlu')">Sommario</button> |
| | Una finestra per la Luna | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px;border-radius: 20px;  text-decoration: none;" onclick="showVideo('FinestraLuna')">Sommario</button> |
| | Traiettorie di ritorno libero | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px;border-radius: 20px;  text-decoration: none;" onclick="showVideo('FRT')">Sommario</button> |
| | Pillole di Apollo | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px;border-radius: 20px;  text-decoration: none;" onclick="showVideo('PilloleApollo')">Sommario</button> |
| **2022** | Interazione Uomo-macchina per la Luna | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px; border-radius: 20px;  text-decoration: none;" onclick="showVideo('UomoMacchina')">Sommario</button> |
| | Quale approccio per andare sulla Luna? | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px;border-radius: 20px;  text-decoration: none;" onclick="showVideo('LOR')">Sommario</button> |
| | Sistemi di navigazione (1/2) | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px; border-radius: 20px; text-decoration: none;" onclick="showVideo('Navigazione_1')">Sommario</button> |
| | Sistemi di navigazione (2/2) | <button  style="background-color: #f0e4cc; color: green; padding: 5px 12px; border-radius: 20px; text-decoration: none;" onclick="showVideo('Navigazione_2')">Sommario</button> |

:::

<br>
