project:
  type: book
  output-dir: ../docs/book
  preview:
    port: 7777
    browser: true

book:
  edition: 1
  favicon: cover.png
  title: "Il cielo per tutti"
  subtitle: "Piccolo zibaldone di astronomia e astronautica"
  date-format: long
  page-navigation: true
  image: cover.png
  publisher: "Editore"
  license: "CC BY-NC"
  sidebar:
    background: light
    search: false
    style: docked
    collapse-level: 6
    border: true
  cover-image: cover.png
  repo-actions: [issue]
  repo-url: https://github.com/alexfum75/prova3/libro
  repo-branch: main
  reader-mode: true

  page-footer: 
    border: true
    center: "Copyright 2026, Alessandro Fumagalli" 
    left: | 
      written by Alessandro Fumagalli
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

  navbar:
    logo: logo.jpeg
    left:
      - text: "Il libro"
        href: index.qmd
      #- text: "Conferenze"
      #  href: conferenze.qmd
        
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/alessandrofumagalli/
      - icon: avatar.png

    background: light
    border: true
    search: false
    tools:
      - icon: github
        href: https://github.com/

format:
  html:
    grid:
      sidebar-width: 280px  # default 250px
      body-width: 950px # default 800px
      margin-width: 200px # default 250px
      gutter-width: 1.5rem  
    toc: true
    toc-location: right
    toc-title: "Contents"
    #toc-depth: 5
    #respect-user-color-scheme: true
    theme:
      dark:
        - cosmo  #slatr
        #- solar.scss
      light: yeti #spacelab


reference-location: margin
citation-location: margin

