project:
  type: book
  output-dir: ../docs/book
  preview:
    port: 7777
    browser: true

execute:
  freeze: auto
  cache: true # for python

book:
  edition: 1
  favicon: cover.png
  title: "Il cielo per tutti"
  subtitle: "Piccolo zibaldone di astronomia e astronautica"
  date-format: long
  page-navigation: true
  image: cover.png
  publisher: "Editore"
  license: "CC BY-NC"
  sidebar:
    background: light
    search: false
    style: docked
    collapse-level: 6
    border: true
  cover-image: cover.png
  reader-mode: false
  page-footer: 
    left: |
      ![Logo](images/Licenza.png){width=110px}
    border: true
    center: "Quest'opera di Alessandro Fumagalli è concessa in licenza sotto la Licenza" 
    right: |
      Copyright 2026
  chapters:
    - index.qmd  

    - introduzione.qmd
    
    - carosello.qmd
    
    - part: "Vicino a noi"
      chapters:
        - TerraDintorni.qmd
        - SistemaTerraLuna.qmd
        - FratelliTerra.qmd
        - AltriMondi.qmd

    - part: "Il planetario"
      chapters:
        - MisuraTempo.qmd      
        - PilloleFisica.qmd
        - MeccanicaCeleste.qmd

    - part: "Oltre noi"
      chapters:
        - Stelle.qmd
        - Universo.qmd
        - Costellazioni.qmd

    - part: "Biografie" 
      chapters:
        - Dante.qmd
        - Biografie.qmd

    - part: "Astronautica"  
      chapters:
      - Sovietici.qmd
      - ProgrammaApollo.qmd
      - ProgrammaArtemis.qmd      
      - AndiamoMarte.qmd      
    
    - glossario.qmd

    #- indice.qmd
    
    - appendici.qmd

  navbar:
    logo: images/logo.jpeg
    left:
      - text: "Home"
        href: ../index.html
        
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/alessandrofumagalli
      - icon: avatar.png

    background: light
    border: true
    search: false

format:
  html:
    fontsize: 17px 
    mainfont: "Armarialbold, sans-serif;"
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnfonts.com">
    grid:
      sidebar-width: 270px  # default 250px
      body-width: 960px # default 800px
      margin-width: 200px # default 250px
      gutter-width: 1.5rem  
    toc: true
    toc-location: right
    toc-title: "Contents"
    #toc-depth: 5
    #respect-user-color-scheme: true
    theme:
      - cosmos
      - ../custom.scss
      #- solar.scss

reference-location: margin
citation-location: margin
